### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by alaframboise** [Esri/esri-system-js#16]
Hey @tomwayson, thanks for putting this together. `esri-systemjs-loader` might be a better name for this one however. Format could be used for others too e.g. `esri-requirejs-loader`.  ;)

**Comment by tomwayson** [comment]
Thanks for the feedback @alaframboise.

Do you think that the name 'esri-system-js' causes any confusion about the purpose of this repo? I'm reluctant to change it w/o good reason since it's already been published to NPM, and that would mean creating a new package and deprecating this one.

I agree that it would be good to be more consistent about how we present the various hacks we use to integrate our Dojo-based API w/ other JavaScript libraries and frameworks. However, I think repo names is the least of our worries.

For example, right now there is no current repo dedicated to integrating w/ requirejs. In fact, if you [google "esri requirejs"](https://www.google.com/search?q=esri+requirejs) the first 2 pages show a bunch of outdated forum posts and repos, most saying that it can't be done. None of them point to the latest thinking on the matter, which is basically [a footnote of the bower section of the JSAPI resources repo](https://github.com/Esri/jsapi-resources/tree/master/3.x/bower/requirejs/src). 

Most of the other integrations are under people's personal github accounts, some, like [esri-webpack](https://github.com/lobsteropteryx/esri-webpack) are not owned by Esri employees.

Even if we did come up w/ a standardized naming format, the other libraries that we're trying to integrate w/ will have their own naming conventions. For example, Ember recommends the `ember-cli-` prefix. I guess [ember-cli-amd](https://github.com/Esri/ember-cli-amd) could have been named "ember-cli-amd-loader", but in Webpack, a "loader" is a very specific thing, so `esri-webpack-loader` would not have been a good choice for the above repo b/c it isn't actually implemented as a Webpack loader.

So, I suggest that the best approach is to let the names fall where they may and let's make sure that there is a central place w/ good Google juice that aggregates and links to all of these integrations.
