### ISSUE TITLE
How to use this in a build?

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-system-js#22]
in #18 @nickcam alludes to creating a local build. We should document how to do that when using esri-system-js. 

@nickcam are you using the [SystemJS builder](https://github.com/systemjs/builder)? If so, w/ gulp, or? Anything you can share about your process (overview/steps, link to repo, snippets, gotchas) would be helpful.

**Comment by nickcam** [comment]
Hi @tomwayson,
I didn't get far with this, had to put it on the backburner due to other priorities.
As I was looking to do this for an Angular2 app I was just using the tools outlined in the Ahead of Time compilation docs page - [https://angular.io/docs/ts/latest/cookbook/aot-compiler.html](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html).

So just compiled it using their ngc compiler and then using rollup to bundle a single build file. Also using gulp to run the tools. I'm not sure if those tools would suit all users of esri-system-js though, it's pretty specific to an Angular 2 app (well ngc is exclusive). 

I had a small project building and running in this setup, but can't find it now, must have deleted it. Will dig it up or recreate it though and post the details in a repo or gist or somewhere.

Only gotcha I can remember is having to set the format in the rollup config to "amd".  
A good point is that using esri-system-js didn't seem to hinder this build process at all - it just seemed to work as it would if it wasn't being used.

**Comment by tomwayson** [comment]
Thanks @nickcam! This is good information!

If you can find the work you did that would be great, but I would say no need to recreate it unless you want to. The above info should at least get people pointed in the right direction.

**Comment by llam001** [comment]
Hi @nickcam,

I tried the [AoT Compilation](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) link you provided using the [QuickStart ](https://angular.io/docs/ts/latest/quickstart.html) project as a base, and then adding the 'esri/Map' dependency.  I had to add the 4.x typings from [jsapi-resources/4.x/typescript/](https://github.com/Esri/jsapi-resources/tree/master/4.x/typescript) to get rid of compile errors.  

For the rollup config, I did update the format to be 'amd' and I also had to include my load.ts file (contents of the [configure step in esri-system-js](https://github.com/Esri/esri-system-js)) as the entry point of the single build file (`entry: 'app/load.js'`), otherwise the rollup would fail.  Here are the contents of my load.ts file:

> esriSystem.register(
>   // array of Esri module names to load and then register with SystemJS
>   [
>     'esri/Map',
>     'esri/views/MapView',
>     'esri/request',
>     'esri/layers/FeatureLayer',
>     'esri/layers/GraphicsLayer'
>   ],
>   // optional callback function
>   function() {
>     // then bootstrap application
>     System.import('./main')
>       .then(null, console.error.bind(console));
>   });

The main entry point to my app is main.ts, but since the rollup only creates a single build.js file, the call to 'System.import('./main')' fails.  I tried removing my load.ts file from the rollup, but again it would complain about dependencies.  Curious how you got this to work.  

Also, did you use the lite server by running 'npm run lite' or were you able to deploy stand alone to a separate web server (e.g. IIS, Tomcat)?

Thanks for any help in the matter!

**Comment by nickcam** [comment]
Hi @llam001, I plan on creating a starter app for .Net Core, using Angular2 and arcigs for my own reference anyway, so will just publish it up as a repo when done. 

It should include the rollup build stuff as well - now I think about it more I have a feeling there were more gotcha's than I mentioned earlier. Will post a comment back in here when it's done...can't give a timeframe though sorry.

**Comment by nickcam** [comment]
@llam001 && @tomwayson. 
I found that project I had with the ngc and rollup build working. Have just published a starter repo for .NET Core apps, the build steps I've used so far are included in it. Hope it helps!
[https://github.com/nickcam/Ang2-Esri-NetCore](https://github.com/nickcam/Ang2-Esri-NetCore)

**Comment by tomwayson** [comment]
Maybe this issue is irrelevant.

Both @nickcam's [Ang2-Esri-NetCore project](https://github.com/nickcam/angular2-esri-netcore/blob/fb26deb0b96a557975fa8f13eb713c4b9d5e3249/angular2-esri-netcore/src/angular2-esri-netcore/gulpfile.js#L143) and @beginor's [ng2-esri-demo](https://github.com/beginor/ng2-esri-demo/blob/c7ed0da46afc0b1b158d3245031427e8e0b46ea3/package.json#L19) use rollup to bundle the application modules, and as far as I understand, SystemJS is not involved in either production build at all.

Closing for now.
