### ISSUE TITLE
How can I use it in a commonjs system such as webpack?

### ISSUE THREAD

**Issue by GISyuezhao** [Esri/esri-system-js#5]
I have successfully run the example you provided, it's amazing！But I'd like to know how can I use arcgis API with angular2 in webpcak. Thank you!

**Comment by tomwayson** [comment]
I'm not aware of any way to do that. 

A few months ago I started to look into using webpack with the bower release of the JSAPI, but I saw  [the issues people were having using webpack w/ Dojo](https://github.com/webpack/webpack/issues/890) and I didn't even bother. It's the same old story. Dojo doesn't think it's worth supporting the AMD spec the way other loaders do, other loaders don't think it's worth supporting Dojo's implementation of the AMD spec, and Esri's JavaScript API team doesn't think that enough of their users care about using other loaders to consider an alternative to Dojo. Therefore, I'm not optimistic about ever being able to use Esri modules in a webpack build.

I think of the Dojo loader as a one way street, it can load non-Dojo AMD/UMD modules, but you can't load Esri/Dojo modules from other loaders.

It _may_ be possible to configure a Dojo's loader to load Angular 2. I haven't looked at the Angular 2 webpack seeds to see how they load the bits and pieces of Angular 2 (angular, rxjs, etc) yet (and I don't have any plans to do so in the immediate future), but maybe those pieces could be loaded by the Dojo loader. This is the pattern we use w/ some other frameworks like [React](https://github.com/odoe/esrijs4-vm-react). It's theoretically possible that kind of thing would work w/ Angular 2. Keep in mind that polyfills may need to be added to the page directly instead of loaded.

It's worth noting that is _not_ the pattern w/ use w/ [Angular 1](https://github.com/Esri/angular-esri-map) or [Ember](https://github.com/Esri/ember-cli-amd) because those frameworks have their own conventions around module loading.

If anyone is able to get Esri/Dojo modules to load w/ webpack, I'd love to be proved wrong. I also would love to hear if anyone can produce a sample of how to run an Angular 2 app via the Dojo loader.

cc @odoe @jpeterson @gavinr @jwasilgeo @ycabon

**Comment by GISyuezhao** [comment]
OK, thanks a lot for your reply. Maybe I should think about it in other way.

**Comment by petedavis** [comment]
So does the requirejs optimizer build example still rely on dojo? 
https://github.com/Esri/jsapi-resources/tree/master/bower/requirejs

I thought that it would be possible to port a requirejs build to a webpack build? Unfortunately have no dojo experience, and the project build uses typescript and webpack. Finding it hard to get this integrated.

**Comment by odoe** [comment]
The RequireJS build does not rely on Dojo, but RequireJS can't build with most of the loader plugins in Dojo either, so you'll never be able to get a single-file build using the RequireJS optimizer, some files will always need to be dynamically loaded. Webpack can build with AMD files, but falls short the same way other build systems do when it tries to resolve the loader plugins. I haven't done much with Webpack, so can't fully comment on it.

**Comment by westfalenxqq** [comment]
anybody intergrated webpack and arcgis js 4.0 successfully？

**Comment by tomwayson** [comment]
Not that I'm aware of.

As I went to copy the above link to the [long-standing issue w/ Webpack being unable to load Dojo modules](https://github.com/webpack/webpack/issues/890), and I came across [dojo-webpack-loader](https://github.com/Nordth/dojo-webpack-loader), which includes [examples](https://github.com/Nordth/dojo-webpack-loader-examples) that would *seem* to indicate that they've gotten past the plugin problems. I've been burned by the Dojo loader too many times to be overly optimistic about that, but I'd say it there's a chance it could work for the ArcGIS API for JavaScript.

Another approach is to configure your build tool to ignore the Esri and Dojo modules and only build your own application code and output it into one or more AMD modules that can be loaded by the Dojo loader. You can then use the CDN build of the ArcGIS API for JavaScript along side your bundled, minified application code. [I've got this working quite nicely using Rollup as the build tool](https://github.com/tomwayson/esri-rollup-example/). The nice thing about this approach is that builds are fast enough to run w/in live reload. My intuition tells me that you could probably do something similar with Webpack using something like the [IgnorePlugin](https://webpack.github.io/docs/list-of-plugins.html#ignoreplugin). One nice thing about Rollup is that it automatically excludes modules it can't resolve (Esri/Dojo) so you don't have to explicitly configure which paths to ignore.

**Comment by lobsteropteryx** [comment]
We've taken a similar approach--loading dojo and the JSAPI as `externals` from CDN, and bundling everything else using webpack.  Took a bit of configuration, but not too bad.  There's a demo here, if it helps anyone:  https://github.com/lobsteropteryx/esri-webpack

**Comment by gund** [comment]
Also tried to this approach to load JSAPI as externals from CDN.  
Works pretty good under my `dev` build however for `production` I am using hashing for bundles (**polyfills, vendors, app**) and in this case those files will be no longer resolved by dojoLoader...  
For now have no idea how to deal with it, if anyone can come up with smthing – will appreciate it.  
  
BTW: Thanks @lobsteropteryx for example

**Comment by tomwayson** [comment]
I'm closing this issue since @lobsteropteryx has demonstrated how to configure a webpack build to use externals, both [with](https://github.com/tomwayson/angular2-esri-example/pull/13) and [without](https://github.com/lobsteropteryx/esri-webpack) Angular 2.

@gund I think your question re: how to build a production build is valid. I think the best place to explore that is w/in a new issue in [obsteropteryx/esri-webpack](https://github.com/lobsteropteryx/esri-webpack/issues). It would be helpful if you could share your webpack config in that issue.

**Comment by gund** [comment]
@tomwayson thanks for your response.

I actually come up with the solution for my problem and generally speaking it's not related to JSAPI directly but how to configure webpack build itself.

Since it might be helpful for someone I created a [gist](https://gist.github.com/gund/6b22d5ffae42849252abc9a689eb656d) where covered my case.

**Comment by dcworldwide** [comment]
I'm working on a Webpack + react + esri js template. So far so good. https://github.com/dcworldwide/esri-webpack

**Comment by tomwayson** [comment]
FYI - I explain how the above solutions work and compare them to the alternative solution offered by [esri-loader](https://github.com/tomwayson/esri-loader) in [this blog post](http://tomwayson.com/2016/11/27/using-the-arcgis-api-for-javascript-in-applications-built-with-webpack/).

**Comment by RoyTinker** [comment]
@tomwayson Thanks for that blog post - very helpful.
